name: general-modelling-birdtracking_maggeo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.0.3
  - pip:
    - markupsafe==2.0.1
    - viresclient==0.10.0
    - chaosmagpy==0.8